---
title: "DataAir_IF"
author: "Yaroslav Davydchuk"
date: "2023-09-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## старт

вантажу бібліотеки і встановлюю робочу папку

```{r}
library(tidyverse) 
library(lubridate) 
library(ggplot2) 

getwd() #displays your working directory
setwd("/media/uarik/S2/Rstudio_projects/DataAir/") 
```

```{r}
jobdata <- read_csv("ECOCITY_Archive_375_2_2019-02-20_2023-09-23.csv", col_names = FALSE)
```

```{r}
colnames(jobdata)

```

```{r}
jobdata <- rename(jobdata, station_ID=X1, coodrinates = X2, date = X3, time = X4, num_of_mes = X5, indicator = X6, unit = X7, value = X8)
colnames(jobdata)
#str(jobdata)
```

```{r}
temp_table <- jobdata %>%
  group_by(indicator, unit) %>%
  summarise(n = round(mean(value), 2))
temp_table
```

```{r}
jobdata <- jobdata %>%
  mutate(value = ifelse(indicator == 'NO₂' & unit == 'ppb', value * 1000, value)) %>%
  mutate(unit = ifelse(indicator == 'NO₂' & unit == 'ppb', 'ppm', unit))

#побідне з тиском. 

jobdata <- jobdata %>%
  mutate(value = ifelse(indicator == 'Pressure' & unit == 'hPa', value * 100, value)) %>%
  mutate(unit = ifelse(indicator == 'Pressure' & unit == 'hPa', 'Pa', unit))
```

```{r}
temp_table <- jobdata %>%
  group_by(indicator, unit) %>%
  summarise(n = round(mean(value), 2))
temp_table
```

Шукаю аномальні значення (але дані потрібно буде видалятипізніше, в зведеній таблиці)

```{r}
temp_table <- jobdata %>%
  group_by(indicator, unit) %>%
  summarise(n = round(mean(value), 2), max = round(max(value), 2), min = round(min(value), 2), sd = round(sd(value), 2))

temp_table
```
далі потрібно переіменувати індикатори, адже наступним кроком буде створення зведеної таблиці, і назви колонок будуть з нижніми індексами (що заборонено в назвах змінних)
```{r}
jobdata <- jobdata %>%
  mutate(indicator = ifelse(indicator == 'CO₂', 'CO2', indicator)) %>%
  mutate(indicator = ifelse(indicator == 'NH₃', 'NH3', indicator)) %>%
  mutate(indicator = ifelse(indicator == 'NO₂', 'NO2', indicator)) %>%
  mutate(indicator = ifelse(indicator == 'O₃', 'O3', indicator)) %>%
  mutate(indicator = ifelse(indicator == 'SO₂', 'SO2', indicator)) 


temp_table2 <- jobdata %>%
  group_by(indicator, unit) %>%
  summarise(n = round(mean(value), 2))

temp_table2
```

